# 包含 Flutter 推荐的 lint 规则
include: package:flutter_lints/flutter.yaml

# 分析器配置
analyzer:
  # 强类型检查
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
    
  # 排除特定文件
  exclude:
    - lib/generated/**
    - lib/**.g.dart

  # 错误级别设置
  errors:
    missing_return: error
    dead_code: warning
    
# lint 规则配置
linter:
  rules:
    # 代码风格规则
    camel_case_types: true
    library_names: true
    avoid_empty_else: true
    cancel_subscriptions: true
    
    # 格式规则
    prefer_single_quotes: true
    always_specify_types: false
    sort_child_properties_last: true
    
    # 使用规则
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
