name: myeyes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter_lifecycle_detector: ^0.0.6
  network_info_plus: ^5.0.3
  volume_control: ^0.1.5
  app_settings: ^5.1.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  flutter_tts: ^3.8.5
  image_picker: ^0.8.3
  flutter_vision: ^1.1.4
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  dio: ^5.4.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/tessdata/
  uses-material-design: true
