org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
systemProp.javax.net.ssl.trustStorePassword=changeit
systemProp.https.protocols=TLSv1.2,TLSv1.3
systemProp.http.protocols=TLSv1.2,TLSv1.3
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
